name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pandoc on Mac
        run: brew install pandoc
        if: matrix.os == 'macos-latest'
      - name: Install pandoc on Linux
        run: sudo apt -y install pandoc
        if: matrix.os == 'ubuntu-latest'
      - name: Install tox
        run: pip install tox tox-gh-actions
      - name: Run tox
        run: tox
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5

  misc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tox_env: [flake8, isort, docs]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install tox
        run: pip install tox
      - name: Run tox
        run: tox -e ${{ matrix.tox_env }}
