name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: '01 07 * * *'

jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8, 3.9]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pandoc on Windows
        run: choco install pandoc
        if: matrix.os == 'windows-latest'
      - name: Install pandoc on Mac
        run: brew install pandoc
        if: matrix.os == 'macos-latest'
      - name: Install pandoc on Linux
        run: sudo apt -y install pandoc
        if: matrix.os == 'ubuntu-latest'
      - name: Install tox
        run: pip install tox tox-gh-actions
      - name: Run tox
        run: tox
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

  misc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tox_env: [flake8, isort, docs]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install tox
        run: pip install tox
      - name: Run tox
        run: tox -e ${{ matrix.tox_env }}
